

COLOURDB =  [
"AQUAMARINE","BLACK","BLUE","BLUE VIOLET",
"BROWN","CADET BLUE","CORAL","CORNFLOWER BLUE",
"CYAN","DARK GREY","DARK GREEN","DARK OLIVE GREEN",
"DARK ORCHID","DARK SLATE BLUE","DARK SLATE GREY DARK TURQUOISE",
"DIM GREY","FIREBRICK","FOREST GREEN","GOLD","GOLDENROD","GREY",
"GREEN","GREEN YELLOW","INDIAN RED","KHAKI","LIGHT BLUE","LIGHT GREY",
"LIGHT STEEL BLUE","LIME GREEN","MAGENTA","MAROON",
"MEDIUM AQUAMARINE","MEDIUM BLUE","MEDIUM FOREST GREEN","MEDIUM GOLDENROD",
"MEDIUM ORCHID","MEDIUM SEA GREEN","MEDIUM SLATE BLUE","MEDIUM SPRING GREEN",
"MEDIUM TURQUOISE","MEDIUM VIOLET RED","MIDNIGHT BLUE","NAVY",
"ORANGE","ORANGE RED","ORCHID","PALE GREEN","PINK","PLUM","PURPLE",
"RED","SALMON","SEA GREEN","SIENNA","SKY BLUE","SLATE BLUE"
]
