# Name:
# Purpose:
#
# Author:       D. Moore
#
# RCS-ID:       $Id: globalConstants.py,v 1.2 2004-12-06 22:22:46 damoore Exp $
#  <copyright>
#  Copyright 2002 BBN Technologies, LLC
#  under sponsorship of the Defense Advanced Research Projects Agency (DARPA).
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the Cougaar Open Source License as published by
#  DARPA on the Cougaar Open Source Website (www.cougaar.org).
#
#  THE COUGAAR SOFTWARE AND ANY DERIVATIVE SUPPLIED BY LICENSOR IS
#  PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
#  IMPLIED, INCLUDING (BUT NOT LIMITED TO) ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND WITHOUT
#  ANY WARRANTIES AS TO NON-INFRINGEMENT.  IN NO EVENT SHALL COPYRIGHT
#  HOLDER BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL
#  DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE OF DATA OR PROFITS,
#  TORTIOUS CONDUCT, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
#  PERFORMANCE OF THE COUGAAR SOFTWARE.
# </copyright>
#


COLOURDB =  [
"AQUAMARINE","BLACK","BLUE","BLUE VIOLET",
"BROWN","CADET BLUE","CORAL","CORNFLOWER BLUE",
"CYAN","DARK GREY","DARK GREEN","DARK OLIVE GREEN",
"DARK ORCHID","DARK SLATE BLUE","DARK SLATE GREY DARK TURQUOISE",
"DIM GREY","FIREBRICK","FOREST GREEN","GOLD","GOLDENROD","GREY",
"GREEN","GREEN YELLOW","INDIAN RED","KHAKI","LIGHT BLUE","LIGHT GREY",
"LIGHT STEEL BLUE","LIME GREEN","MAGENTA","MAROON",
"MEDIUM AQUAMARINE","MEDIUM BLUE","MEDIUM FOREST GREEN","MEDIUM GOLDENROD",
"MEDIUM ORCHID","MEDIUM SEA GREEN","MEDIUM SLATE BLUE","MEDIUM SPRING GREEN",
"MEDIUM TURQUOISE","MEDIUM VIOLET RED","MIDNIGHT BLUE","NAVY",
"ORANGE","ORANGE RED","ORCHID","PALE GREEN","PINK","PLUM","PURPLE",
"RED","SALMON","SEA GREEN","SIENNA","SKY BLUE","SLATE BLUE"
]
