# Name:
# Purpose:
#
# Author:       D. Moore
#
# RCS-ID:       $Id: zoomer.py,v 1.6 2004-12-06 22:18:20 damoore Exp $
#  <copyright>
#  Copyright 2002 BBN Technologies, LLC
#  under sponsorship of the Defense Advanced Research Projects Agency (DARPA).
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the Cougaar Open Source License as published by
#  DARPA on the Cougaar Open Source Website (www.cougaar.org).
#
#  THE COUGAAR SOFTWARE AND ANY DERIVATIVE SUPPLIED BY LICENSOR IS
#  PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
#  IMPLIED, INCLUDING (BUT NOT LIMITED TO) ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND WITHOUT
#  ANY WARRANTIES AS TO NON-INFRINGEMENT.  IN NO EVENT SHALL COPYRIGHT
#  HOLDER BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL
#  DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE OF DATA OR PROFITS,
#  TORTIOUS CONDUCT, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
#  PERFORMANCE OF THE COUGAAR SOFTWARE.
# </copyright>
#


#zoomView:
#given a societymodel, draws it at the chosen level of zoom granularity
import sys
import re

import wx

DEFAULT_ZOOMLEVEL = 1

viewLevelData = [
{"BOXWIDTH":   10,"BOXHEIGHT":  6, "WIDTHSPACING": 4, "HEIGHTSPACING":  30,"HEIGHTSPACING": 30,"FONTSIZE":6},
{"BOXWIDTH":   20,"BOXHEIGHT": 12, "WIDTHSPACING":  8, "HEIGHTSPACING":  60,"HEIGHTSPACING": 60,"FONTSIZE":8},
{"BOXWIDTH":   50,"BOXHEIGHT": 30, "WIDTHSPACING":20, "HEIGHTSPACING": 150,"HEIGHTSPACING":150,"FONTSIZE":12},
{"BOXWIDTH": 100,"BOXHEIGHT": 60, "WIDTHSPACING":40, "HEIGHTSPACING": 300,"HEIGHTSPACING":300,"FONTSIZE":24},
]

ZEROLEVEL = 0
MAXWIDTH = 8000
MAXHEIGHT= 1000
BOXWIDTH = 50
BOXHEIGHT = 30
WIDTHSPACING = 20
HEIGHTSPACING = 150

CURRENTLEVEL = DEFAULT_ZOOMLEVEL

def setLevel(level=1): 
        global CURRENTLEVEL
        if level < 0: level = 0
        if level > 3: level = 3
        CURRENTLEVEL = level
def getLevel(): return CURRENTLEVEL
